spring:
  application:
    name: restaurant
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:restaurantdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

api:
  security:
    token:
      secret: ${JWT_SECRET:05b0f768-fe7b-49aa-b934-44ef29634de3}